### ISSUE TITLE
No documentation on the PEG implementation used

### ISSUE THREAD

**Issue by guillemj** [naoina/toml#29]
Please document that the PEG source requires the https://github.com/pointlander/peg project to build. I had to dig through git history to see that this was the project from an old .travis.yml entry. :)

**Comment by aviau** [comment]
Would #30 be a duplicate?

Guillem, did you manage to generate a working parse.peg.go file using pointlander/peg?

**Comment by guillemj** [comment]
Alexandre, yeah seems like a dupe. I had not tested because I didn't have those dependencies packaged yet, now that you have done so I've tried. and checking the newly generated output, there's only a couple of changes needed in error.go. I'm posting a pull request to fix that.

**Comment by aviau** [comment]
> I'm posting a pull request to fix that.

Thank you for the effort! :)

**Comment by guillemj** [comment]
Ok, please see the above pull, please let me know if something seems wrong, or if it does not work for you. Thanks!
