### ISSUE TITLE
How modifying a key?

### ISSUE THREAD

**Issue by samiwt** [naoina/toml#42]
Does the library incorporate the possibility of modifying a key?
Eg:
[**server**]
**addr** = _"127.0.0.1"_
**port** = _8080_
Update **server** set **addr** = _":: 1"_
Update **server** set **port** = _3000_

Given

[**server**]
**addr** = _"::1"_
**port** = _3000_

**Comment by fjl** [comment]
You can do this by parsing the config, updating the Go value and then serializing it out again.
