### ISSUE TITLE
Ignore additional fields

### ISSUE THREAD

**Issue by mbertschler** [naoina/toml#5]
My usecase is having a config file for multiple projects, and one project only uses a part of the structure of the full config file. The problem is that `Unmarshal()` fails if there are fields in the config file that are not defined in my struct. 

Could this library ignore fields from the file that are not available in the target struct like (this is how for example `encoding/json` would handle this)?

Thanks

**Comment by naoina** [comment]
It can't do that. However, I might change to that behavior in future.
